/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Estructural.Paciente;
import java.rmi.RemoteException;
//import Servicios.servicioPaciente;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.IServicioPaciente;
import model.ServicioLocalPaciente;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author crist
 */
public class GUIMostarPacientes extends javax.swing.JFrame {
    private IServicioPaciente servicio;
 DefaultTableModel modelo = new  DefaultTableModel();
   //servicioPaciente servicio = new servicioPaciente();
 //ArrayList<Paciente> paciente = servicio.getListaPacientes();
    /**
     * Creates new form GUIMostarPacientes
     */
    public GUIMostarPacientes() {
        servicio = ServicioLocalPaciente.getServicio();
        initComponents();
        this.setLocationRelativeTo(null);
        modelo.addColumn("Nombre");
        modelo.addColumn("Documento");
        modelo.addColumn("correo");
        modelo.addColumn("telefono");
        modelo.addColumn("Sexo");
        jTablePaciente.setModel(modelo);
       
     
    }
    
    public void barras ()
        {
            int masculino = 0, femenino = 0;
            try{
                DefaultCategoryDataset cd = new DefaultCategoryDataset();
                
                for (int i = 0; i < jTablePaciente.getRowCount(); i++) {
                    if(jTablePaciente.getValueAt(i,4).equals("masculino")){
                        masculino ++;
                    }
                    else if(jTablePaciente.getValueAt(i, 4).equals("femenino")){
                        femenino ++;
                    }
                }
                cd.addValue(masculino, "masculino","");
                cd.addValue(femenino, "Femenino","");
                
                JFreeChart fc = ChartFactory.createBarChart3D("","Cantidad de Pacientes por sexo", "Cantidad", cd, PlotOrientation.VERTICAL, true, true, true);
                ChartFrame cf = new ChartFrame("Cantidad de Pacientes por sexo", fc);
                cf.setSize(600, 600);
                cf.setLocationRelativeTo(null);
                cf.setVisible(true);
                
            } catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"" + e);
            }
            
        } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePaciente = new javax.swing.JTable();
        butListar = new javax.swing.JButton();
        butSalir = new javax.swing.JButton();
        btnGrafico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTablePaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Documento", "Correo", "Telefono", "Sexo"
            }
        ));
        jScrollPane1.setViewportView(jTablePaciente);

        butListar.setText("Listar");
        butListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butListarActionPerformed(evt);
            }
        });

        butSalir.setText("Salir");
        butSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSalirActionPerformed(evt);
            }
        });

        btnGrafico.setText("Grafico");
        btnGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGrafico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butListar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrafico)
                    .addComponent(butListar)
                    .addComponent(butSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butListarActionPerformed
               
    modelo.setRowCount(0);
        try {
            for(int i = 0; i < servicio.tamaño(); i++)
            {
                
                Object[] fila = {
                    
                    servicio.obtener(i).getNombre(),
                    servicio.obtener(i).getDocumento(),
                    servicio.obtener(i).getCorreo(),
                    servicio.obtener(i).getTelefono(),
                    servicio.obtener(i).getSexo()                     
                };
                modelo.addRow(fila);
            }
            
            /*String matriz [][] = new String[servicio.tama�o()] [4];
            
            for(int i = 0; i < servicio.tama�o(); i++)
            {
            matriz[i][0] = servicio.obtener(i).getNombre();
            matriz[i][1] = servicio.obtener(i).getDocumento();
            matriz[i][2] = servicio.obtener(i).getCorreo();
            matriz[i][3] = servicio.obtener(i).getTelefono();
            
            
            jTablePaciente.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
            }
            ));
            
            }*/
        } catch (RemoteException ex) {
            Logger.getLogger(GUIMostarPacientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_butListarActionPerformed

    private void btnGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoActionPerformed
        // TODO add your handling code here:
        barras();
    }//GEN-LAST:event_btnGraficoActionPerformed

    private void butSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_butSalirActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrafico;
    private javax.swing.JButton butListar;
    private javax.swing.JButton butSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePaciente;
    // End of variables declaration//GEN-END:variables
}
